"""
Element Sizing Configuration

This module contains all element sizing constants including dimensions,
margins, padding, font sizes, and other measurements.
"""

# Import alignment constants
from .layout import (
    TEXT_ALIGN_LEFT,
    TEXT_ALIGN_CENTER,
    TEXT_ALIGN_RIGHT,
    ALIGN_LEFT,
    ALIGN_CENTER,
    ALIGN_RIGHT,
)

# ===== HEADER ELEMENTS =====
HEADER_H1_SIZE = "2.5rem"
HEADER_H2_SIZE = "2rem"
HEADER_H3_SIZE = "1.75rem"
HEADER_H4_SIZE = "1.5rem"
HEADER_H5_SIZE = "1.25rem"

HEADER_H1_LINE_HEIGHT = "1.2"
HEADER_H2_LINE_HEIGHT = "1.3"
HEADER_H3_LINE_HEIGHT = "1.4"
HEADER_H4_LINE_HEIGHT = "1.4"

# Header alignment options
HEADER_ALIGN_LEFT = TEXT_ALIGN_LEFT
HEADER_ALIGN_CENTER = TEXT_ALIGN_CENTER
HEADER_ALIGN_RIGHT = TEXT_ALIGN_RIGHT

# ===== CONTAINER SIZING =====
CONTAINER_MAX_WIDTH = "1200px"
CONTAINER_MARGIN = "0 auto"
CONTAINER_PADDING = "20px"

# ===== BUTTON SIZING =====
BUTTON_HEIGHT = "40px"
BUTTON_MIN_WIDTH = "100px"
BUTTON_PADDING = "10px 20px"
BUTTON_BORDER_RADIUS = "5px"
BUTTON_FONT_SIZE = "14px"

# Button alignment options
BUTTON_ALIGN_LEFT = TEXT_ALIGN_LEFT
BUTTON_ALIGN_CENTER = TEXT_ALIGN_CENTER
BUTTON_ALIGN_RIGHT = TEXT_ALIGN_RIGHT

# ===== INPUT FIELD SIZING =====
INPUT_HEIGHT = "40px"
INPUT_PADDING = "8px 12px"
INPUT_BORDER_RADIUS = "4px"
INPUT_FONT_SIZE = "14px"
INPUT_MIN_WIDTH = "120px"

# Input alignment options
INPUT_ALIGN_LEFT = TEXT_ALIGN_LEFT
INPUT_ALIGN_CENTER = TEXT_ALIGN_CENTER
INPUT_ALIGN_RIGHT = TEXT_ALIGN_RIGHT

# ===== UPLOAD AREA SIZING =====
UPLOAD_AREA_WIDTH = "100%"
UPLOAD_AREA_HEIGHT = "60px"
UPLOAD_AREA_LINE_HEIGHT = "60px"
UPLOAD_AREA_MIN_HEIGHT = "100px"
UPLOAD_AREA_BORDER_RADIUS = "8px"

# Upload area alignment options
UPLOAD_ALIGN_LEFT = TEXT_ALIGN_LEFT
UPLOAD_ALIGN_CENTER = TEXT_ALIGN_CENTER
UPLOAD_ALIGN_RIGHT = TEXT_ALIGN_RIGHT

# ===== MAP ELEMENT SIZING =====
MAP_WIDTH = "100%"
MAP_HEIGHT = 500  # in pixels
MAP_MIN_HEIGHT = "400px"
MAP_MAX_HEIGHT = "800px"
MAP_BORDER_RADIUS = "8px"

# Map alignment options
MAP_ALIGN_LEFT = ALIGN_LEFT
MAP_ALIGN_CENTER = ALIGN_CENTER
MAP_ALIGN_RIGHT = ALIGN_RIGHT

# ===== CHECKBOX SIZING =====
CHECKBOX_SIZE = "16px"
CHECKBOX_MARGIN_RIGHT = "8px"
CHECKBOX_LABEL_FONT_SIZE = "14px"
CHECKBOX_GROUP_PADDING = "12px"

# Checkbox alignment options
CHECKBOX_ALIGN_LEFT = TEXT_ALIGN_LEFT
CHECKBOX_ALIGN_CENTER = TEXT_ALIGN_CENTER
CHECKBOX_ALIGN_RIGHT = TEXT_ALIGN_RIGHT

# ===== LIST ELEMENT SIZING =====
LIST_ITEM_PADDING = "8px 12px"
LIST_ITEM_MARGIN = "2px 0"
LIST_FONT_SIZE = "14px"
LIST_LINE_HEIGHT = "1.5"

# List alignment options
LIST_ALIGN_LEFT = TEXT_ALIGN_LEFT
LIST_ALIGN_CENTER = TEXT_ALIGN_CENTER
LIST_ALIGN_RIGHT = TEXT_ALIGN_RIGHT
